import React from 'react'

const Type =[
    {
        id: 1,
        title: 'T-Shirt',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img:'https://png.pngtree.com/png-clipart/20201205/ourmid/pngtree-pink-cartoon-t-shirt-png-image_2481875.jpg',
        categories:"Mens",
        size:["S","M","L","XL","XXL"],
        color:["Red","Blue","Green","Yellow","Black"],
        price: 500,
    },
    {
        id: 2,
        title: 'Cap',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img:'https://png.pngtree.com/element_our/20190529/ourmid/pngtree-blue-fashion-hip-hop-cap-illustration-image_1217214.jpg',
        categories:"Kids",
        size:["S","M","L","XL","XXL"],
        color:["Red","Blue","Green","Yellow","Black"],
        price: 300,
    },
    {
        id: 3,
        title: 'Laptop',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img:'https://png.pngtree.com/png-vector/20200428/ourmid/pngtree-gradient-isometric-laptop-mockup-vector-isometric-laptop-png-element-png-image_2195665.jpg',
        categories:"Grocery",
        price: 79000,
    },
    {
        id: 4,
        title: 'Books',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img:'https://png.pngtree.com/png-clipart/20220314/ourmid/pngtree-pile-of-books-3d-icon-education-and-student-concept-png-image_4491793.png',
        categories:"kids",
        price: 1003,
    },
    {
        id: 5,
        title: 'Coat',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img:'https://png.pngtree.com/png-clipart/20221121/ourmid/pngtree-formal-suit-full-dress-transparent-psd-png-image_6473363.png',
        categories:"Mens",
        price: 3999,
    },
    {
        id: 6,
        title: 'Lamp',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img: 'https://png.pngtree.com/png-clipart/20190116/ourmid/pngtree-yellow-table-lamp-desk-furniture-writing-desk-lamp-cartoon-illustration-png-image_403734.jpg',
        categories:"Electronics",
        price: 1023,
    },
    {
        id: 7,
        title: 'Bag',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img: 'https://png.pngtree.com/png-vector/20220723/ourmid/pngtree-paper-bag-mockup-dsign-png-image_6039487.png',
        categories:"Kids",
        price: 399,
    },
    {
        id: 8,
        title: 'Pants',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img: 'https://png.pngtree.com/element_our/20190603/ourmid/pngtree-blue-denim-shorts-image_1454642.jpg',
        categories:"Mens",
        price: 1500,
    },
    {
        id: 9,
        title: 'Cold Drinks',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img: 'https://png.pngtree.com/element_our/20190604/ourmid/pngtree-a-bottle-of-cold-drink-cola-illustration-image_1467498.jpg',
        categories:"Kids",
        price: 120,
    },
    {
        id: 10,
        title: 'Camera',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img: 'https://png.pngtree.com/png-clipart/20190117/ourmid/pngtree-camera-digital-camera-technology-electronic-png-image_431407.jpg',
        categories:"Electronics",
        color:["Red","blue","Pink","white"],
        price: 9500,
    },
    {
        id: 11,
        title: 'Shoes',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img: 'https://png.pngtree.com/element_our/20190530/ourmid/pngtree-men-s-black-glossy-shoes-image_1244455.jpg',
        categories:"Mens",
        color:["Red","blue","Pink","white"],
        price: 1120,
    },
    {
        id: 12,
        title: 'Headphones',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
        img: 'https://png.pngtree.com/png-clipart/20201129/ourmid/pngtree-headphones-png-image_2452681.jpg',
        categories:"Electronics",
        color:["Red","blue","Pink","white"],
        price: 1099,
    },
]

export default Type
